import random
import math
from environment import Agent, Environment
from planner import RoutePlanner
from simulator import Simulator
from math import exp

class LearningAgent(Agent):
    """ An agent that learns to drive in the Smartcab world.
        This is the object you will be modifying. """ 

    def __init__(self, env, learning=False, epsilon=1.0, alpha=0.5):
        super(LearningAgent, self).__init__(env)     # Set the agent in the evironment 
        self.planner = RoutePlanner(self.env, self)  # Create a route planner
        self.valid_actions = self.env.valid_actions  # The set of valid actions

        # Set parameters of the learning agent
        self.learning = learning # Whether the agent is expected to learn
        self.Q = dict()          # Create a Q-table which will be a dictionary of tuples
        self.epsilon = epsilon   # Random exploration factor
        self.alpha = alpha       # Learning factor

        ###########
        ## TO DO ##
        ###########
        # Set any additional class parameters as needed
        self.testing = False
        self.t = 0.0 # t - number of tries

    def reset(self, destination=None, testing=False):
        """ The reset function is called at the beginning of each trial.
            'testing' is set to True if testing trials are being used
            once training trials have completed. """

        # Select the destination as the new location to route to
        self.planner.route_to(destination)
        
        ########### 
        ## TO DO ##
        ###########
        # Update epsilon using a decay function of your choice
        # Update additional class parameters as needed
        # If 'testing' is True, set epsilon and alpha to 0
        self.testing = testing
        self.t = self.t + 1.0
        
        if self.testing:
            self.epsilon = 0.0
            self.alpha   = 0.0
        else:
            # First Q-learning implementation: epsilon = epsilon - 0.05
            # self.epsilon = self.epsilon - 0.05
            
            # Improved Q-learning implementation: epsilon = 1 / (t*t)
            self.epsilon = 1.0 / (self.t * self.t) # 1 / t*t

        return None

    def build_state(self):
        """ The build_state function is called when the agent requests data from the 
            environment. The next waypoint, the intersection inputs, and the deadline 
            are all features available to the agent. """

        # Collect data about the environment
        waypoint = self.planner.next_waypoint() # The next waypoint 
        inputs = self.env.sense(self)           # Visual input - intersection light and traffic
        deadline = self.env.get_deadline(self)  # Remaining deadline

        ########### 
        ## TO DO ##
        ###########
        
        # NOTE : you are not allowed to engineer eatures outside of the inputs available.
        # Because the aim of this project is to teach Reinforcement Learning, we have placed 
        # constraints in order for you to learn how to adjust epsilon and alpha, and thus learn about the balance between exploration and exploitation.
        # With the hand-engineered features, this learning process gets entirely negated.
        
        # Set 'state' as a tuple of relevant data for the agent        
        state = (waypoint, inputs) #None

        return state


    def get_maxQ(self, state):
        """ The get_max_Q function is called when the agent is asked to find the
            maximum Q-value of all actions based on the 'state' the smartcab is in. """

        ########### 
        ## TO DO ##
        ###########
        # Calculate the maximum Q-value of all actions for a given state
        
        # recommended method per code review
        maxQ = max(self.Q[str(state)].values())
        
        """
        maxQ = 0.0
        state_str = str(state)
        if  state_str in self.Q.keys():
            adict = self.Q[state_str]
            print("Q-list: state_str  ", state_str)
            for key in adict.keys():
                value = adict[key]
                print("Q-list: action = ", key, " ,value = ", value) 
                if value > maxQ:
                    maxQ = value
        else:
            print("state_str = ", state_str, " not in Q list!")
        """

        #maxQ = None
        print("max Q value = ", maxQ)

        return maxQ 

    def createQ(self, state):
        """ The createQ function is called when a state is generated by the agent. """

        ########### 
        ## TO DO ##
        ###########
        # When learning, check if the 'state' is not in the Q-table
        # If it is not, create a new dictionary for that state
        #   Then, for each action available, set the initial Q-value to 0.0
        
        # Code review comment: Make sure your Q-Table is ONLY initialized when Learning == True
        if (not self.learning):
            return
        
        # convert state to string
        state_str = str(state)
        if state_str in self.Q.keys():
            return
        else:
            dict_item = dict()
            for action in self.valid_actions:
                dict_item[action] = 0.0
            self.Q[state_str] = dict_item

        return

    def getQ(self, state, action):
        """ Yuefeng add this function for calculating running average of rewards. """
        qvalue = 0.0
        state_str = str(state)
        if state_str in self.Q.keys():
            vdict = self.Q[state_str]
            if action in vdict.keys():  
                qvalue = vdict[action]
            else:
                print("getQ: action not in vdict!!!")
        else:
            print("getQ: state not in self.Q!!!")

        return qvalue
    
    def setQ(self, state, action, qvalue):
        """ Yuefeng add this function for calculating running average of rewards and then updating Q value. """
        state_str = str(state)
        if state_str in self.Q.keys():    
            vdict = self.Q[state_str]
            if action in vdict.keys():         
                vdict[action] = qvalue
            else:
                print("setQ: action not in vdict!!!") 
        else:
            print("setQ: state not in self.Q!!!")

        return

    def choose_action(self, state):
        """ The choose_action function is called when the agent is asked to choose
            which action to take, based on the 'state' the smartcab is in. """

        # Set the agent state and default action
        self.state = state
        self.next_waypoint = self.planner.next_waypoint()
        action = None

        ########### 
        ## TO DO ##
        ###########
        # When not learning, choose a random action
        # When learning, choose a random action with 'epsilon' probability
        # Otherwise, choose an action with the highest Q-value for the current state
        # Be sure that when choosing an action with highest Q-value that you randomly select between actions that "tie".
        state_str = str(state)
        action_index = random.randint(0, 3)
        if (not self.learning):
            action = self.valid_actions[action_index]
        else:
            random_number = random.uniform(0.0, 1.0)
            if random_number <= self.epsilon:
                action = self.valid_actions[action_index]
                print("exploration, action = ", action)
            else:
                # recommended method per code review
                best_actions = [action for action in self.valid_actions if self.Q[str(state)][action] == max(self.Q[str(state)].values())]
                action = random.choice(best_actions)
                
                """
                maxQ = self.get_maxQ(state)
                best_actions = []
                dict_item = self.Q[state_str]
                for action in self.valid_actions:
                    qvalue = dict_item[action]
                    if qvalue >= maxQ:
                        best_actions.append(action)
                number_of_actions = len(best_actions)
                if number_of_actions < 1:
                    print("choose_action error: best actions list is empty!")
                    action = None
                elif number_of_actions == 1:
                    action = best_actions[0]
                    print("only one best action = ", action)
                else:
                    best_action_index = random.randint(0, number_of_actions - 1)
                    action = best_actions[best_action_index]
                    print("multiple best actions, randomly selected action = ", action)
                """
        
        return action


    def learn(self, state, action, reward):
        """ The learn function is called after the agent completes an action and
            receives a reward. This function does not consider future rewards 
            when conducting learning. """

        ########### 
        ## TO DO ##
        ###########
        # When learning, implement the value iteration update rule
        #   Use only the learning rate 'alpha' (do not use the discount factor 'gamma')
        state_str = str(state)
        if self.learning:          
                
            # get the previous Q value for the pair of (state, action)
            qvalue = self.getQ(state, action)
            print("current Q value = ", qvalue)
                
            # get alpha
            alpha = self.alpha
                
            # calculate new Q value
            new_qvalue = (1.0 - alpha) * qvalue + alpha * reward
            print("new Q value = ", new_qvalue)
                
            # update Q value
            self.setQ(state, action, new_qvalue)
           
        else:
            None

        return


    def update(self):
        """ The update function is called when a time step is completed in the 
            environment for a given trial. This function will build the agent
            state, choose an action, receive a reward, and learn if enabled. """

        state = self.build_state()          # Get current state
        self.createQ(state)                 # Create 'state' in Q-table
        action = self.choose_action(state)  # Choose an action
        reward = self.env.act(self, action) # Receive a reward
        self.learn(state, action, reward)   # Q-learn

        return
        

def run():
    """ Driving function for running the simulation. 
        Press ESC to close the simulation, or [SPACE] to pause the simulation. """

    ##############
    # Create the environment
    # Flags:
    #   verbose     - set to True to display additional output from the simulation
    #   num_dummies - discrete number of dummy agents in the environment, default is 100
    #   grid_size   - discrete number of intersections (columns, rows), default is (8, 6)
    env = Environment()
    
    ##############
    # Create the driving agent
    # Flags:
    #    * learning - set to True to force the driving agent to use Q-learning
    #    * epsilon  - continuous value for the exploration factor, default is 1
    #    * alpha    - continuous value for the learning rate, default is 0.5
    
    # First implementation of Q-learning
    # agent = env.create_agent(LearningAgent, learning = True)
    
    # Improved implementation of Q-learning
    # alpha 0.9, tolerance 0.000001 - Reliability A, safety A
    agent = env.create_agent(LearningAgent, learning = True, alpha = 0.9)
    
    ##############
    # Follow the driving agent
    # Flags:
    #   enforce_deadline - set to True to enforce a deadline metric
    env.set_primary_agent(agent, enforce_deadline = True)

    ##############
    # Create the simulation
    # Flags:
    #   update_delay - continuous time (in seconds) between actions, default is 2.0 seconds
    #   display      - set to False to disable the GUI if PyGame is enabled
    #   log_metrics  - set to True to log trial and simulation results to /logs
    #   optimized    - set to True to change the default log file name
    
    # First implementation of Q-learning
    # sim = Simulator(env, update_delay = 0.01, log_metrics = True, optimized = False)
    
    # Improved implementation of Q-learning
    sim = Simulator(env, update_delay = 0.01, log_metrics = True, optimized = True)
    
    ##############
    # Run the simulator
    # Flags:
    #   tolerance  - epsilon tolerance before beginning testing, default is 0.05 
    #   n_test     - discrete number of testing trials to perform, default is 0
    
    # First implementation of Q-learning
    # sim.run(n_test = 10)
    
    # Improved implementation of Q-learning
    # alpha 0.9, tolerance 0.000001 - Reliability A, safety A
    sim.run(n_test = 40, tolerance = 0.000001)


if __name__ == '__main__':
    run()
